### ISSUE TITLE
Getting : Failed to subcribe for filter LoanStarted.  The subscription is disposed.

### ISSUE THREAD

**Issue by stephen101** [ConsenSys/eventeum#139]
All of a sudden in the last few hours I've been getting errors registering events, none of my code has changed. I did see that Infura have degraded websocket performance. Could that be the issue and if so is there a workaround? It's quite urgent as it is affecting users.

**From status.infura.io :**
"We are experiencing performance degradation for certain filter requests (specifically eth_getFilterLogs) on our websocket endpoint. Note that this performance degradation is limited only to filter requests and has no effect on subscriptions. Users requesting 'eth_getFilterLogs' may be seeing an increase in error responses and/or possible disconnects. We ask that users use 'eth_getLogs' instead of 'eth_getFilterLogs' to avoid this issue."

**From the Eventeum logs :**
Failed to subcribe for filter LoanStarted.  The subscription is disposed.\n\tat net.consensys.eventeum.chain.service.Web3jService.registerEventListener(Web3jService.java:141) ~[eventeum-core-0.8.1-KAURI.jar!/:0.8.1-KAURI]\n\tat net.consensys.eventeum.service.DefaultSubscriptionService.registerContractEventFilter(DefaultSubscriptionService.java:258) [eventeum-core-0.8.1-KAURI.jar!/:0.8.1-KAURI]\n\tat net.consensys.eventeum.service.DefaultSubscriptionService.doRegisterContractEventFilter(DefaultSubscriptionService.java:215) [eventeum-core-0.8.1-KAURI.jar!/:0.8.1-KAURI]\n\tat net.consensys.eventeum.service.DefaultSubscriptionService.registerContractEventFilter(DefaultSubscriptionService.java:100) [eventeum-core-0.8.1-KAURI.jar!/:0.8.1-KAURI]\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_242]\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_242]\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242]\n\tat java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242]\n\tat org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) [spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206) [spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat com.sun.proxy.$Proxy137.registerContractEventFilter(Unknown Source) [na:na]\n\tat net.consensys.eventeum.endpoint.ContractEventFilterEndpoint.addEventFilter(ContractEventFilterEndpoint.java:50) [eventeum-core-0.8.1-KAURI.jar!/:0.8.1-KAURI]\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_242]\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_242]\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242]\n\tat java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242]\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:215) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:142) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) [spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) [spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) [spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) [spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) [spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:998) [spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:901) [spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:875) [spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) [spring-boot-actuator-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:154) [spring-boot-actuator-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]\n\tat org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:122) [spring-boot-actuator-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]\n\tat org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:107) [spring-boot-actuator-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.12.jar!/:9.0.12]\n\tat java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]\n",

**Comment by craigwilliams84** [comment]
Hey Stephen, sorry about the delayed response.  We are using `eth_getFilterLogs` in Eventeum so this Infura degradation may be the cause of the issue that you're seeing.  Is it still occurring? If it is very urgent, you could try running the latest SNAPSHOT.  We are no longer using `eth_getFilterLogs` in the next release.  I can't guarantee the stability of the `development` branch though, although I've tested quite thoroughly (its close to being released).

**Comment by stephen101** [comment]
I tried using the snapshot from a couple of days ago but I was getting errors on startup. I see you pushed a new snapshot, I'll give that a go quickly and get back to you.

**Comment by stephen101** [comment]
Ok, so it's still happening with the 0.8.1 build. When I try use this image : https://hub.docker.com/layers/eventeum/eventeum/0.8.1-SNAPSHOT/images/sha256-ad3db05357d9758e300979fb89471ee04b84fc099751bc6adf505dddc38ad4d0?context=explore

I get the following errors :

10:26:44.585 [main] ERROR org.springframework.boot.SpringApplication - Application run failed

Info
2020-07-09 12:26:38.688 SAST
10:26:38.687 [background-preinit] DEBUG org.hibernate.validator.internal.engine.resolver.TraversableResolvers - Found javax.persistence.Persistence on classpath containing 'getPersistenceUtil'. Assuming JPA 2 environment. Trying to instantiate JPA aware TraversableResolver
Info
2020-07-09 12:26:38.693 SAST
10:26:38.692 [background-preinit] DEBUG org.hibernate.validator.internal.engine.resolver.TraversableResolvers - Instantiated JPA aware TraversableResolver of type org.hibernate.validator.internal.engine.resolver.JPATraversableResolver.
Info
2020-07-09 12:26:38.775 SAST
10:26:38.773 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based Validator configuration.
Info
2020-07-09 12:26:38.783 SAST
10:26:38.783 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via TCCL
Info
2020-07-09 12:26:38.793 SAST
10:26:38.787 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via Hibernate Validator's class loader
Info
2020-07-09 12:26:38.794 SAST
10:26:38.794 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - No META-INF/validation.xml found. Using annotation based configuration only.
Info
2020-07-09 12:26:40.199 SAST
10:26:40.198 [background-preinit] DEBUG org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator - Loaded expression factory via original TCCL
Info
2020-07-09 12:26:40.293 SAST
10:26:40.293 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator as ValidatorFactory-scoped message interpolator.
Info
2020-07-09 12:26:40.293 SAST
10:26:40.293 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.resolver.JPATraversableResolver as ValidatorFactory-scoped traversable resolver.
Info
2020-07-09 12:26:40.294 SAST
10:26:40.294 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.util.ExecutableParameterNameProvider as ValidatorFactory-scoped parameter name provider.
Info
2020-07-09 12:26:40.295 SAST
10:26:40.295 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.DefaultClockProvider as ValidatorFactory-scoped clock provider.
Info
2020-07-09 12:26:40.296 SAST
10:26:40.296 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.
Info
2020-07-09 12:26:44.586 SAST
10:26:44.585 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
Info
2020-07-09 12:26:44.586 SAST
java.lang.IllegalArgumentException: Invalid argument syntax: --spring.config.additional-location= at org.springframework.core.env.SimpleCommandLineArgsParser.parse(SimpleCommandLineArgsParser.java:75) at org.springframework.core.env.SimpleCommandLinePropertySource.<init>(SimpleCommandLinePropertySource.java:90) at org.springframework.boot.DefaultApplicationArguments$Source.<init>(DefaultApplicationArguments.java:76) at org.springframework.boot.DefaultApplicationArguments.<init>(DefaultApplicationArguments.java:42) at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) at net.consensys.eventeumserver.Application.main(Application.java:29) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Show log summary
Expand nested fields
Copy to clipboard
{
textPayload: "java.lang.IllegalArgumentException: Invalid argument syntax: --spring.config.additional-location=
	at org.springframework.core.env.SimpleCommandLineArgsParser.parse(SimpleCommandLineArgsParser.java:75)
	at org.springframework.core.env.SimpleCommandLinePropertySource.<init>(SimpleCommandLinePropertySource.java:90)
	at org.springframework.boot.DefaultApplicationArguments$Source.<init>(DefaultApplicationArguments.java:76)
	at org.springframework.boot.DefaultApplicationArguments.<init>(DefaultApplicationArguments.java:42)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at net.consensys.eventeumserver.Application.main(Application.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

**Comment by craigwilliams84** [comment]
There was an error in the docker start script...I've just pushed a fix, so try the newest SNAPSHOT now.

**Comment by stephen101** [comment]
Great, looks like that fixed it. I can subscribe to events again too. Thanks! 

What is the ETA on a release so I can schedule time to upgrade?

**Comment by Grey007** [comment]
I am still getting the same error as above. 

I've pulled the latest development branch, ran everything and deployed. 

Getting the following errors:

io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException


	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)


	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)


	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.error(FlowableCreate.java:292)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:536)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.tryOnError(FlowableCreate.java:486)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:274)


	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:74)


	at io.reactivex.Flowable.subscribe(Flowable.java:14479)


	at io.reactivex.Flowable.subscribe(Flowable.java:14416)


	at io.reactivex.Flowable.subscribe(Flowable.java:14306)


	at net.consensys.eventeum.chain.service.Web3jService.registerEventListener(Web3jService.java:123)


	at net.consensys.eventeum.service.DefaultSubscriptionService.registerContractEventFilter(DefaultSubscriptionService.java:258)


	at net.consensys.eventeum.service.DefaultSubscriptionService.doRegisterContractEventFilter(DefaultSubscriptionService.java:215)


	at net.consensys.eventeum.service.DefaultSubscriptionService.lambda$registerContractEventFilterWithRetries$1(DefaultSubscriptionService.java:109)


	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)


	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)


	at net.consensys.eventeum.service.DefaultSubscriptionService.registerContractEventFilterWithRetries(DefaultSubscriptionService.java:109)


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)


	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)


	at java.util.concurrent.FutureTask.run(FutureTask.java:266)


	at java.lang.Thread.run(Thread.java:748)


Caused by: java.lang.NullPointerException


	at org.web3j.protocol.core.filters.LogFilter.process(LogFilter.java:46)


	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:119)


	at org.web3j.protocol.core.filters.Filter.run(Filter.java:69)


	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:88)


	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogFlowable$2(JsonRpc2_0Rx.java:78)


	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)


	... 20 more


Exception in thread "SimpleAsyncTaskExecutor-2" io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException


	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)


	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)


	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.error(FlowableCreate.java:292)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:536)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.tryOnError(FlowableCreate.java:486)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:274)


	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:74)


	at io.reactivex.Flowable.subscribe(Flowable.java:14479)


	at io.reactivex.Flowable.subscribe(Flowable.java:14416)


	at io.reactivex.Flowable.subscribe(Flowable.java:14306)


	at net.consensys.eventeum.chain.service.Web3jService.registerEventListener(Web3jService.java:123)


	at net.consensys.eventeum.service.DefaultSubscriptionService.registerContractEventFilter(DefaultSubscriptionService.java:258)


	at net.consensys.eventeum.service.DefaultSubscriptionService.doRegisterContractEventFilter(DefaultSubscriptionService.java:215)


	at net.consensys.eventeum.service.DefaultSubscriptionService.lambda$registerContractEventFilterWithRetries$1(DefaultSubscriptionService.java:109)


	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)


	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)


	at net.consensys.eventeum.service.DefaultSubscriptionService.registerContractEventFilterWithRetries(DefaultSubscriptionService.java:109)


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)


	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)


	at java.util.concurrent.FutureTask.run(FutureTask.java:266)


	at java.lang.Thread.run(Thread.java:748)


Caused by: java.lang.NullPointerException


	at org.web3j.protocol.core.filters.LogFilter.process(LogFilter.java:46)


	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:119)


	at org.web3j.protocol.core.filters.Filter.run(Filter.java:69)


	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:88)


	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogFlowable$2(JsonRpc2_0Rx.java:78)


	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)


	... 20 more


2020-07-10 07:20:09.072 [SimpleAsyncTaskExecutor-2] ERROR net.consensys.eventeum.service.DefaultSubscriptionService: doRegisterContractEventFilter - Error registering filter Uniswap_DAI_ETH


net.consensys.eventeum.chain.service.BlockchainException: Failed to subcribe for filter Uniswap_DAI_ETH.  The subscription is disposed.


	at net.consensys.eventeum.chain.service.Web3jService.registerEventListener(Web3jService.java:141) ~[eventeum-core-0.8.1-KAURI.jar!/:0.8.1-KAURI]


	at net.consensys.eventeum.service.DefaultSubscriptionService.registerContractEventFilter(DefaultSubscriptionService.java:258) [eventeum-core-0.8.1-KAURI.jar!/:0.8.1-KAURI]


	at net.consensys.eventeum.service.DefaultSubscriptionService.doRegisterContractEventFilter(DefaultSubscriptionService.java:215) [eventeum-core-0.8.1-KAURI.jar!/:0.8.1-KAURI]


	at net.consensys.eventeum.service.DefaultSubscriptionService.lambda$registerContractEventFilterWithRetries$1(DefaultSubscriptionService.java:109) [eventeum-core-0.8.1-KAURI.jar!/:0.8.1-KAURI]


	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) ~[spring-retry-1.2.2.RELEASE.jar!/:na]


	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164) ~[spring-retry-1.2.2.RELEASE.jar!/:na]


	at net.consensys.eventeum.service.DefaultSubscriptionService.registerContractEventFilterWithRetries(DefaultSubscriptionService.java:109) [eventeum-core-0.8.1-KAURI.jar!/:0.8.1-KAURI]


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]


	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252]


	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252]


	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]


	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]


	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]


	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_252]


	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_252]


io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException


	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)


	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)


	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.error(FlowableCreate.java:292)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:536)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.tryOnError(FlowableCreate.java:486)


	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:274)


	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:74)


	at io.reactivex.Flowable.subscribe(Flowable.java:14479)


	at io.reactivex.Flowable.subscribe(Flowable.java:14416)


	at io.reactivex.Flowable.subscribe(Flowable.java:14306)


	at net.consensys.eventeum.chain.service.Web3jService.registerEventListener(Web3jService.java:123)


	at net.consensys.eventeum.service.DefaultSubscriptionService.registerContractEventFilter(DefaultSubscriptionService.java:258)


	at net.consensys.eventeum.service.DefaultSubscriptionService.doRegisterContractEventFilter(DefaultSubscriptionService.java:215)


	at net.consensys.eventeum.service.DefaultSubscriptionService.lambda$registerContractEventFilterWithRetries$1(DefaultSubscriptionService.java:109)


	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)


	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)


	at net.consensys.eventeum.service.DefaultSubscriptionService.registerContractEventFilterWithRetries(DefaultSubscriptionService.java:109)


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)


	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)


	at java.util.concurrent.FutureTask.run(FutureTask.java:266)


	at java.lang.Thread.run(Thread.java:748)


Caused by: java.lang.NullPointerException


	at org.web3j.protocol.core.filters.LogFilter.process(LogFilter.java:46)


	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:119)


	at org.web3j.protocol.core.filters.Filter.run(Filter.java:69)


	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:88)


	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogFlowable$2(JsonRpc2_0Rx.java:78)


	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)


	... 20 more

**Comment by craigwilliams84** [comment]
@Grey007 It seems that you aren't running the latest development version somehow....the method `Web3jService.registerEventListener` that I see in the stack trace isn't used anymore in the latest version.

**Comment by craigwilliams84** [comment]
@stephen101 Hopefully version 0.9.0 will be released early next week.

**Comment by craigwilliams84** [comment]
@stephen101 Just FYI, I discovered a minor issue which meant I've had to refactor some things and want to run the release candidate for a few days to test before releasing, so the release will probably not drop until the weekend now.

**Comment by craigwilliams84** [comment]
This issue should be fixed in release 0.9.0....please open again if it still occurs.
